"""empty message

Revision ID: 1205cd3b2d60
Revises: d5f342f80cea
Create Date: 2024-05-01 14:44:03.559648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1205cd3b2d60'
down_revision = 'd5f342f80cea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
