"""empty message

Revision ID: 2f107bcfcbc7
Revises: 9fecdb7aaa36
Create Date: 2024-04-28 19:57:30.907026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f107bcfcbc7'
down_revision = '9fecdb7aaa36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
