"""empty message

Revision ID: 3b07874e2387
Revises: 8241e789ca43
Create Date: 2024-07-05 01:41:41.784124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b07874e2387'
down_revision = '8241e789ca43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
