"""empty message

Revision ID: 6e431ccec15c
Revises: 143d4e6d8430
Create Date: 2024-04-27 23:34:31.132648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e431ccec15c'
down_revision = '143d4e6d8430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prediction', sa.String(length=80), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=80), nullable=False))
        batch_op.drop_column('filename')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('location')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('detections', schema=None) as batch_op:
        batch_op.drop_column('prediction')

    # ### end Alembic commands ###
