"""empty message

Revision ID: 8241e789ca43
Revises: 1205cd3b2d60
Create Date: 2024-06-10 15:13:01.823176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8241e789ca43'
down_revision = '1205cd3b2d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
