"""empty message

Revision ID: 870975db6a9d
Revises: 9ebf04a00e7c
Create Date: 2024-07-05 10:23:02.437276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '870975db6a9d'
down_revision = '9ebf04a00e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
