"""empty message

Revision ID: 9ebf04a00e7c
Revises: c2ba7f3a386f
Create Date: 2024-07-05 01:49:54.559651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ebf04a00e7c'
down_revision = 'c2ba7f3a386f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
