"""empty message

Revision ID: 9fecdb7aaa36
Revises: 6e431ccec15c
Create Date: 2024-04-28 00:00:52.042494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fecdb7aaa36'
down_revision = '6e431ccec15c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
