"""empty message

Revision ID: b451e6f36c20
Revises: 870975db6a9d
Create Date: 2024-09-11 17:16:51.187133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b451e6f36c20'
down_revision = '870975db6a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
