"""empty message

Revision ID: c2ba7f3a386f
Revises: 3b07874e2387
Create Date: 2024-07-05 01:46:10.949637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2ba7f3a386f'
down_revision = '3b07874e2387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
