"""empty message

Revision ID: cd9d3d7b4f9a
Revises: da1718dd063e
Create Date: 2024-04-29 12:05:07.427203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd9d3d7b4f9a'
down_revision = 'da1718dd063e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
