"""empty message

Revision ID: d5f342f80cea
Revises: cd9d3d7b4f9a
Create Date: 2024-04-29 13:59:50.531891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5f342f80cea'
down_revision = 'cd9d3d7b4f9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
